/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Đăng nhập bằng email hoặc số điện thoại
         * @description Trả access token trong body và đặt refresh token vào cookie httpOnly.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng xuất: thu hồi refresh token và xóa cookie */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lấy access token mới bằng refresh token trong cookie */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Xin link upload
         * @description Tạo bản ghi file (PENDING) và trả link PUT có hạn. Sau khi PUT xong phải gọi complete.
         */
        post: operations["uploadUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Xác nhận đã upload
         * @description Kiểm tra nội dung trên storage đúng loại và dung lượng; sai thì xóa file.
         */
        post: operations["complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{id}/download-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Xin link tải file (có hạn) */
        get: operations["downloadUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Thông tin người dùng hiện tại, vai trò và các cơ sở được phép */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DownloadUrlResponse: {
            /** Format: date-time */
            expiresAt: string;
            url: string;
        };
        FileResponse: {
            /** Format: uuid */
            id: string;
            mimeType: string;
            originalName: string;
            /**
             * Format: uuid
             * @description Rỗng = dùng chung toàn chuỗi
             */
            schoolId?: string;
            /** Format: int64 */
            sizeBytes: number;
            /** @enum {string} */
            status: "PENDING" | "READY";
        };
        LoginRequest: {
            /**
             * @description Email hoặc số điện thoại
             * @example owner@preschool.local
             */
            identifier: string;
            password: string;
            /** @description Giữ đăng nhập 7 ngày; bỏ trống/false = hết khi đóng trình duyệt */
            rememberMe?: boolean;
        };
        MeResponse: {
            /** @description Có vai trò cấp chuỗi: được chọn "Tất cả cơ sở" */
            chainWide: boolean;
            email: string;
            fullName: string;
            /** Format: uuid */
            id: string;
            phone?: string;
            roles: components["schemas"]["RoleGrant"][];
            /** @description Các cơ sở được phép chọn trên header */
            schools: components["schemas"]["SchoolSummary"][];
        };
        /** @description Lỗi theo RFC 7807 */
        Problem: {
            /** @description Mã lỗi máy đọc, ví dụ INVALID_CREDENTIALS */
            code?: string;
            /** @description Thông điệp tiếng Việt hiển thị cho người dùng */
            detail?: string;
            /** @description Lỗi từng trường khi dữ liệu không hợp lệ */
            errors?: {
                field: string;
                message: string;
            }[];
            instance?: string;
            /** Format: int32 */
            status: number;
            /** @description Tiêu đề tiếng Việt theo mã HTTP */
            title: string;
            type?: string;
        };
        RoleGrant: {
            /** @enum {string} */
            role: "OWNER" | "CHAIN_ADMIN" | "ACCOUNTANT" | "PRINCIPAL" | "TEACHER" | "NURSE" | "KITCHEN" | "STAFF";
            /**
             * Format: uuid
             * @description Rỗng = toàn chuỗi
             */
            schoolId?: string;
        };
        SchoolSummary: {
            code: string;
            /** Format: uuid */
            id: string;
            name: string;
        };
        TokenResponse: {
            accessToken: string;
            /**
             * Format: int64
             * @description Số giây còn hiệu lực
             */
            expiresIn: number;
            /** @example Bearer */
            tokenType: string;
        };
        UploadUrlRequest: {
            /** @example application/pdf */
            contentType: string;
            /** @example hop-dong.pdf */
            fileName: string;
            /**
             * Format: uuid
             * @description Cơ sở sở hữu file; bỏ trống = cơ sở đang chọn (hoặc toàn chuỗi nếu đang chọn "Tất cả cơ sở")
             */
            schoolId?: string;
            /**
             * Format: int64
             * @description Kích thước file (byte)
             */
            sizeBytes: number;
        };
        UploadUrlResponse: {
            /** Format: date-time */
            expiresAt: string;
            file: components["schemas"]["FileResponse"];
            /** @description Header bắt buộc gửi kèm khi PUT */
            headers: {
                [key: string]: string;
            };
            /** @example PUT */
            method: string;
            /** @description Link PUT nội dung file lên storage */
            uploadUrl: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Lỗi (RFC 7807, thông điệp tiếng Việt) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Đã đăng xuất */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Lỗi (RFC 7807, thông điệp tiếng Việt) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Lỗi (RFC 7807, thông điệp tiếng Việt) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    uploadUrl: {
        parameters: {
            query?: never;
            header?: {
                /** @description Cơ sở đang chọn (UUID). Bỏ trống = tất cả cơ sở trong phạm vi của người dùng. */
                "X-School-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadUrlRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UploadUrlResponse"];
                };
            };
            /** @description Lỗi (RFC 7807, thông điệp tiếng Việt) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    complete: {
        parameters: {
            query?: never;
            header?: {
                /** @description Cơ sở đang chọn (UUID). Bỏ trống = tất cả cơ sở trong phạm vi của người dùng. */
                "X-School-Id"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FileResponse"];
                };
            };
            /** @description Lỗi (RFC 7807, thông điệp tiếng Việt) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    downloadUrl: {
        parameters: {
            query?: never;
            header?: {
                /** @description Cơ sở đang chọn (UUID). Bỏ trống = tất cả cơ sở trong phạm vi của người dùng. */
                "X-School-Id"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DownloadUrlResponse"];
                };
            };
            /** @description Lỗi (RFC 7807, thông điệp tiếng Việt) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeResponse"];
                };
            };
            /** @description Lỗi (RFC 7807, thông điệp tiếng Việt) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
